## NumPy 라이브러리 불러오기


In [1]:
import numpy as np
print(np.__version__)

1.22.4


In [2]:
import numpy
print(numpy.__version__)

1.22.4


## 리스트를 배열로 변환

In [6]:
temp = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
temp_array = np.array(temp)
print(temp)
print(temp_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print(type(temp))
print(type(temp_array))
print(temp_array.shape)
print(temp_array.ndim)

<class 'list'>
<class 'numpy.ndarray'>
(10,)
1


- 첫번째 인수를 출력

In [12]:
temp_array[1]

2

In [13]:
temp_array[-1]

10

## 사칙연산

In [16]:
score1 = [10, 15, 45, 60, 87]
score2 = [30, 40, 94, 84, 73]

score1 + score2

[10, 15, 45, 60, 87, 30, 40, 94, 84, 73]

In [17]:
score1_arr = np.array(score1)
score2_arr = np.array(score2)

result = score1_arr + score2_arr

In [21]:
np.min(result) # 40, 55, 139, 144, 160

40

In [23]:
np.max(result) # 40, 55, 139, 144, 160

160

In [24]:
np.sum(result) # 40, 55, 139, 144, 160

538

## 배열(행렬)의 생성
- 0차원부터 3차원까지로 구성

In [28]:
temp_arr = np.array(30)
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)

30
<class 'numpy.ndarray'>
()


In [31]:
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)

(3,)
1


## 2차원
- 정형 데이터(엑셀 데이터)

In [33]:
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_arr.shape)
print(temp_arr.ndim)

(2, 3)
2


## 3차원
- 이미지 데이터

In [34]:
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(temp_arr.shape)
print(temp_arr.ndim)

(2, 2, 3)
3


In [35]:
temp_arr = np.array([1, 2, 3, 4], ndmin=3)
print(temp_arr.shape)
print(temp_arr.ndim)

(1, 1, 4)
3


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다

In [39]:
temp_arr = np.zeros((5, 10))
temp_arr.dtype

dtype('float64')

- 모두 1로 채운다

In [38]:
temp_arr = np.ones((5, 10))
temp_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- 임의의 상수값으로 채운다

In [40]:
temp_arr = np.full((2, 3), 10)
temp_arr

array([[10, 10, 10],
       [10, 10, 10]])

- 최소 및 최대 숫자의 범위를 정해두고,구간별로 값을 생성하는 코드를 작성함

In [42]:
temp_arr = np.linspace(5, 10, 5)
temp_arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

- np.arange()

In [44]:
temp_arr = np.arange(1, 100, 4)
temp_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

- 임의의 난수 생성

In [50]:
from numpy.random import rand
x = rand()
print(x)

0.7583793117639038


In [48]:
from numpy import random
x = random.rand()
print(x)

0.39379150924492423


In [49]:
import numpy as np
x = np.random.rand()
print(x)

0.3326403815914619


## 배열 연산
- 덧셈 : np.add()
- 뺄셈 : np.subtract()
- 곱셈 : np.multifly()
- 나눗셈 : np.divide()

In [52]:
import numpy as np

array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

# 덧셈
result = np.add(array_01, array_02)
result

array([11, 22, 33])

In [54]:
# 뺄셈
result = np.subtract(array_01, array_02)
result

array([ -9, -18, -27])

In [55]:
# 곱셈
result = np.multiply(array_01, array_02)
result

array([10, 40, 90])

In [56]:
# 나눗셈
result = np.divide(array_01, array_02)
result

array([0.1, 0.1, 0.1])

In [57]:
array_01 = np.array([1, 2, 3])
array_02 = np.array([1, 2, 3])

result = np.power(array_01, array_02)
print(result)

[ 1  4 27]


## 소숫점 정렬
- 소수점 절삭

- 코드는 실행속도 체크

In [64]:
%%time

temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.21 ms, sys: 17 µs, total: 1.23 ms
Wall time: 1.22 ms


In [63]:
%%time

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 643 µs, sys: 0 ns, total: 643 µs
Wall time: 612 µs


- 소숫점 자리에서 반올림

In [61]:
temp_arr = np.around([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

In [62]:
temp_arr = np.round([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

- 소숫점 모두 내린다

In [71]:
import time

# Start time
start_time = time.time()

temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)

# End time
end_time = time.time()

# Execution time
execution_time = end_time - start_time

print("Execution time:", execution_time)

[-2.  1.]
Execution time: 0.0013048648834228516


In [72]:
# Start time
start_time = time.time()

temp_arr = np.ceil([-1.23456, 1.23456])
print(temp_arr)

# End time
end_time = time.time()

# Execution time
execution_time = end_time - start_time

print("Execution time:", execution_time)

[-1.  2.]
Execution time: 0.002056121826171875


## 조건문
- where : 조건식 1개일 때 활용
- select : 다중조건일 때 활용

In [73]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.where

In [74]:
np.where(temp_arr < 5, temp_arr, 10 * temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

-np.select

In [75]:
temp_arr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr * 3, temp_arr + 10]

np.select(cond_list, choice_list, default=temp_arr)

array([10, 11,  2,  3,  4,  5, 18, 21, 24, 27])